/**
 * Generates public/test-full-demo.xlsx — one upload to exercise most 1.0 features.
 * Usage: npm run generate:full-demo
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import * as XLSX from "xlsx";

const readmeRows = [
  ["FeedLayer 1.0 — full demo upload"],
  [""],
  ["When uploading this file:"],
  ["1. Sheet picker appears — choose Full_Demo_Catalog (not this README sheet)."],
  ["2. Optional: re-upload and pick Variant_Grouping to test multi-SKU grouping only."],
  [""],
  ["What Full_Demo_Catalog exercises:"],
  ["• Messy headers → column mapping (desc, img, stock_status, sale_price, colour…)"],
  ["• Variant rows P-V01 / SKU-A|B|C → merged into one product"],
  ["• Missing price, image, description, policies → readiness gaps"],
  ["• USD / EUR / CNY prices → minor-unit normalization"],
  ["• Availability: in stock, out of stock, limited, preorder, in_stock, empty"],
  ["• Weak vs strong descriptions → scoring spread"],
  ["• Chinese product copy on one row"],
];

/** Messy headers on purpose — maps via columnMapping aliases */
const catalogHeaders = [
  "parent_id",
  "merchant_sku",
  "product_name",
  "desc",
  "sale_price",
  "iso_currency",
  "stock_status",
  "product_type",
  "img",
  "colour",
  "size",
  "material",
  "volume",
  "return_policy_url",
  "shipping_policy_url",
  "supplier_desc",
];

const catalogRows: string[][] = [
  // Strong baseline row
  [
    "P-2001",
    "BTL-500-BLK",
    "Insulated Bottle 500ml",
    "Double-wall stainless steel bottle. Keeps drinks cold 24h or hot 12h.",
    "24.99",
    "USD",
    "in stock",
    "Drinkware",
    "https://images.example.com/demo/bottle-500.jpg",
    "Black",
    "500ml",
    "stainless steel",
    "500ml",
    "https://example.com/returns",
    "https://example.com/shipping",
    "Vendor spec: BPA-free lid",
  ],
  // Same product_id → variant merge (color variant)
  [
    "P-2001",
    "BTL-500-WHT",
    "Insulated Bottle 500ml",
    "Double-wall stainless steel bottle. White finish.",
    "24.99",
    "USD",
    "in stock",
    "Drinkware",
    "https://images.example.com/demo/bottle-500-white.jpg",
    "White",
    "500ml",
    "stainless steel",
    "500ml",
    "https://example.com/returns",
    "https://example.com/shipping",
    "",
  ],
  // Missing description + policies
  [
    "P-2002",
    "LAMP-MIN",
    "Minimal Desk Lamp",
    "",
    "45.00",
    "USD",
    "limited",
    "Home / Lighting",
    "https://images.example.com/demo/lamp.jpg",
    "Matte White",
    "",
    "ABS plastic",
    "",
    "",
    "",
    "",
  ],
  // EUR currency
  [
    "P-2003",
    "MAT-EU",
    "Yoga Mat Pro 6mm",
    "High-density non-slip mat for home and studio practice.",
    "34.50",
    "EUR",
    "in stock",
    "Fitness",
    "https://images.example.com/demo/yogamat.jpg",
    "Blue",
    "6mm",
    "TPE",
    "183 x 61 cm",
    "https://example.com/returns",
    "",
    "",
  ],
  // CNY + Chinese copy
  [
    "P-2004",
    "CN-THERMOS",
    "不锈钢保温杯 500ml",
    "双层真空保温，曜石黑，适合日常通勤。",
    "129",
    "CNY",
    "in stock",
    "Drinkware",
    "https://images.example.com/demo/thermos-cn.jpg",
    "曜石黑",
    "500ml",
    "不锈钢",
    "500ml",
    "",
    "https://example.com/shipping",
    "",
  ],
  // out of stock
  [
    "P-2005",
    "CASE-IP15",
    "iPhone 15 Slim Case",
    "Thin TPU case with raised camera lip.",
    "16.99",
    "USD",
    "out of stock",
    "Accessories",
    "https://images.example.com/demo/case.jpg",
    "Clear",
    "One Size",
    "TPU",
    "",
    "https://example.com/returns",
    "https://example.com/shipping",
    "",
  ],
  // preorder
  [
    "P-2006",
    "BLEND-PORT",
    "Portable Blender 450ml",
    "USB rechargeable blender for smoothies on the go.",
    "59.99",
    "USD",
    "preorder",
    "Kitchen Appliances",
    "https://images.example.com/demo/blender.jpg",
    "Green",
    "",
    "plastic",
    "450 ml",
    "",
    "https://example.com/shipping",
    "",
  ],
  // in_stock underscore enum
  [
    "P-2007",
    "WATCH-BAND",
    "Silicone Watch Band 22mm",
    "Soft silicone band compatible with 22mm lugs.",
    "12.00",
    "USD",
    "in_stock",
    "Accessories",
    "https://images.example.com/demo/watchband.jpg",
    "Navy",
    "22mm",
    "silicone",
    "",
    "https://example.com/returns",
    "",
    "",
  ],
  // missing price
  [
    "P-2008",
    "MYSTERY-BOX",
    "Mystery Accessory Box",
    "Surprise accessory bundle — price TBD.",
    "",
    "USD",
    "limited",
    "Misc",
    "https://images.example.com/demo/mystery.jpg",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  // missing image
  [
    "P-2009",
    "TOWEL-GYM",
    "Microfiber Gym Towel",
    "Quick-dry towel for gym and travel.",
    "9.99",
    "USD",
    "in stock",
    "Fitness",
    "",
    "Grey",
    "Large",
    "microfiber",
    "",
    "https://example.com/returns",
    "https://example.com/shipping",
    "",
  ],
  // weak short description
  [
    "P-2010",
    "MUG-BASIC",
    "Basic Ceramic Mug",
    "Nice mug.",
    "8.50",
    "USD",
    "in stock",
    "Drinkware",
    "https://images.example.com/demo/mug.jpg",
    "White",
    "350ml",
    "ceramic",
    "350ml",
    "",
    "",
    "",
  ],
  // piped colors
  [
    "P-2011",
    "CAP-UNI",
    "Unisex Baseball Cap",
    "Adjustable cotton cap with embroidered logo.",
    "18.00",
    "USD",
    "in stock",
    "Accessories",
    "https://images.example.com/demo/cap.jpg",
    "Black|Navy|Khaki",
    "One Size",
    "cotton",
    "",
    "https://example.com/returns",
    "https://example.com/shipping",
    "",
  ],
  // lowercase category (normalization)
  [
    "P-2012",
    "RES-BAND",
    "Resistance Band Set",
    "Set of 5 latex bands with carry bag.",
    "22.99",
    "USD",
    "in stock",
    "fitness",
    "https://images.example.com/demo/bands.jpg",
    "Multi",
    "",
    "latex",
    "",
    "",
    "",
    "",
  ],
  // missing category
  [
    "P-2013",
    "GADGET-X",
    "Unknown Gadget",
    "Miscellaneous gadget for testing uncategorized items.",
    "5.99",
    "USD",
    "in stock",
    "",
    "https://images.example.com/demo/gadget.jpg",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  // empty availability
  [
    "P-2014",
    "CABLE-USBC",
    "USB-C Charge Cable 2m",
    "Braided USB-C to USB-C cable rated 60W.",
    "11.99",
    "USD",
    "",
    "Accessories",
    "https://images.example.com/demo/cable.jpg",
    "Black",
    "2m",
    "nylon braid",
    "",
    "https://example.com/returns",
    "",
    "",
  ],
  // Inline variant group P-V01 (3 SKUs → 1 product on results)
  ["P-V01", "SKU-A", "Widget Pro", "Widget Pro base model.", "10.00", "USD", "in stock", "Misc", "https://images.example.com/a.jpg", "Red", "S", "ABS", "", "", "", ""],
  ["P-V01", "SKU-B", "Widget Pro", "Widget Pro mid size.", "12.00", "USD", "in stock", "Misc", "https://images.example.com/b.jpg", "Blue", "M", "ABS", "", "", "", ""],
  ["P-V01", "SKU-C", "Widget Pro", "Widget Pro large.", "14.00", "USD", "out of stock", "Misc", "https://images.example.com/c.jpg", "Green", "L", "ABS", "", "", "", ""],
];

const variantHeaders = ["product_id", "sku", "title", "desc", "price", "currency", "availability", "category", "image_url", "color", "size"];
const variantRows: string[][] = [
  ["P-GRP-1", "V-RED-S", "Classic Tee", "Soft cotton tee.", "19.99", "USD", "in stock", "Apparel", "https://images.example.com/tee-red-s.jpg", "Red", "S"],
  ["P-GRP-1", "V-RED-M", "Classic Tee", "Soft cotton tee.", "19.99", "USD", "in stock", "Apparel", "https://images.example.com/tee-red-m.jpg", "Red", "M"],
  ["P-GRP-1", "V-BLU-M", "Classic Tee", "Soft cotton tee.", "19.99", "USD", "limited", "Apparel", "https://images.example.com/tee-blu-m.jpg", "Blue", "M"],
  ["P-GRP-1", "V-BLU-L", "Classic Tee", "Soft cotton tee.", "21.99", "USD", "in stock", "Apparel", "https://images.example.com/tee-blu-l.jpg", "Blue", "L"],
  ["P-GRP-2", "V-HAT-1", "Bucket Hat", "Lightweight summer hat.", "15.00", "USD", "preorder", "Apparel", "https://images.example.com/hat.jpg", "Beige", "One Size"],
  ["P-GRP-2", "V-HAT-2", "Bucket Hat", "Lightweight summer hat.", "15.00", "USD", "in stock", "Apparel", "https://images.example.com/hat-2.jpg", "Olive", "One Size"],
];

const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(readmeRows), "README");
XLSX.utils.book_append_sheet(
  wb,
  XLSX.utils.aoa_to_sheet([catalogHeaders, ...catalogRows]),
  "Full_Demo_Catalog",
);
XLSX.utils.book_append_sheet(
  wb,
  XLSX.utils.aoa_to_sheet([variantHeaders, ...variantRows]),
  "Variant_Grouping",
);

const out = join(process.cwd(), "public", "test-full-demo.xlsx");
writeFileSync(out, XLSX.write(wb, { type: "buffer", bookType: "xlsx" }));
console.log(`Wrote ${out}`);
console.log("Sheets: README | Full_Demo_Catalog (main) | Variant_Grouping");
console.log(`Full_Demo_Catalog: ${catalogRows.length} data rows`);
